### ISSUE TITLE
MyQ Account set up with Google - SmartThings won't sign in to the account

### ISSUE THREAD

**Issue by AdventureJon** [hjdhjd/myq#330]
**Describe The Problem:**
I have installed the driver and edge connector (windows executable) and they appear to be working.  I was able to add MyQ-Controller to my SmartThings hub.  When filling in my credentials in the settings, two things occurred.  

1) My MyQ account was set up with Google authentication.  The driver does not seem to be able to use this option and I do not know how to fix this since my account is already set up on MyQ.  When I try, MyQStatus stays on "Awaiting Credentials".

2) When I enter my password - it begins with a lowercase letter.   In MyQ-Controller settings, the first letter appears as uppercase, yet going into the password again reveals it is entered correctly as lowercase.

Is there a way for me to use this solution?  It seems to be exactly what I am looking for if I can get it working.

**To Reproduce:**
1) Set up MyQ account using Google Authentication.
2) Attempt to connect MyQ-Controller to your MyQ account

**Logs:**
I have not been able to figure out how to get to the logs

```
Show the myQ API logs here.
Remove any sensitive information.
```

**Screenshots:**

**Comment by hjdhjd** [comment]
Appreciate the report. This is a known limitation and I have no immediate plans to support non-myQ-native logins at this time. I might look into this in the future, but I’ve got other priorities at the moment.

Google, Apple, etc. logins that aren’t native myQ accounts won’t work.

Create a myQ account, setup your garage door openers, and you’re good to go. If for a variety of reasons you don’t want to do that, you’re going to be unable to use this library for now.

Not the most satisfying answer, I’m sure, but it’s where we’re at right now. Thanks!

**Comment by AdventureJon** [comment]
Thank you for the quick response and appreciate your efforts on this
awesome integration.   After working on this for a couple of days, I was
able to switch my MyQ account by going through the "Forgot Password"
process in a normal browser.  This solved the issue by giving me a password
specific to MyQ account.   I'm continuing through the process to iron out
the remaining issues.
