### ISSUE TITLE
Allow manually specifying myq-cloud 'zone' or automatically re-try other zone on "address not found" errors

### ISSUE THREAD

**Issue by Danimal4326** [hjdhjd/myq#362]
**Is your feature request related to a problem? Please describe:**
I noticed that connections to myQ servers is not very robust.  I noticed that lately my garage door didn't open at all using their home bridge plugin, and I was seeing a lot of  "myQ API: Hostname or IP address not found." errors in my logs.

I went and did some digging, literally wit the 'dig' command to see what the urls hardcoded in the myq module were resolving to and which were failing.  Most often, the requests to accounts.myq-cloud.com and devices.myq-cloud.com
I noticed they are using Azure TrafficManager for balancing.  My dns resolutions for these were going through  accounts-east.myq-cloud.com and devices-east.myq-cloud.com

As a hunch, I tried to see if there was a "west" server for both of those, and there was.  I changed the code in the module (my-api.js) to use the "west" server and all my "address not found" errors went away. My garage door opens again via homekit!!

FYI, there there are "west" and "east" server for all their servers on myq-clound.com:
* partner-identity-east.myq-cloud.com -> partner-identity-west.myq-cloud.com
* devices-east.myq-cloud.com -> devices-west.myq-cloud.com
* accounts-east.myq-cloud.com -> accounts-west.myq-cloud.com
* account-devices-lamp-east.myq-cloud.com -> account-devices-lamp-west.myq-cloud.com
* account-devices-gdo-east.myq-cloud.com -> account-devices-gdo-west.myq-cloud.com

**Describe the solution you'd like:**
The feature request is to either be able to manually specify the "zone" to use, or always try one zone, and on a "ENOTFOUND" error, automatically re-try the other zone server.

**Describe alternatives you've considered:**
Manually editing the source to force a particular zone

**Additional context:**

**Comment by Danimal4326** [comment]
re-freshing

**Comment by Danimal4326** [comment]
ping

**Comment by hjdhjd** [comment]
Thanks for the suggestion and highlighting this. I'll incorporate something into a future revision. Much appreciated!

**Comment by hjdhjd** [comment]
As an FYI: the library doesn't currently discriminate which server it goes to...it uses devices.myq-cloud.com, for example. The DNS (Azure in this case), is pointing you toward east vs west. 😄 

Thanks.

**Comment by Danimal4326** [comment]
Yeah, I get that.  But I've noticed that the west servers have been more stable for some reason! 🤷‍♂️
