### ISSUE TITLE
After NPM installation, I get an error while using it

### ISSUE THREAD

**Issue by RedondoBoony** [hjdhjd/myq#409]
**Describe The Problem:**
After installing myq using 'npm install @hjdhjd/myq', I am not able to use it in IoBroker.
I do have a folder '/opt/iobroker/node_modules/iobroker.javascript/node_modules/@hjdhjd/myq/' but there is no subfolder 'dist' in it.
the myq-folder only contains 3 files: LICENSE.md, package.json, README.md

See the error message below.
What am I doing wrong?

**Logs:**
```
javascript.0 (12914) script.js.Garage: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/node_modules/@hjdhjd/myq/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by jarz** [comment]
This isn't the ioBroker adapter. Try [`ioBroker.myq`](https://github.com/pixcept/ioBroker.myq) instead.

**Comment by RedondoBoony** [comment]
Yes I know but the IoBroker Adapter only works 1x here, after the first installation/login.
Thereafter I am getting login errors using the same login data.

Thats why I have coded my own script using the hjdhjd/MyQ project (qnd the iobroker javascript adapter)

Worked before but now it seems like I am not able to get a good installation of it using NPM.

**Comment by jarz** [comment]
Unfortunately, it seems to work fine for me:
```
 ~/t/t/node_modules > exa --tree @hjdhjd/myq/
@hjdhjd/myq
├── dist
│  ├── index.d.ts
│  ├── index.js
│  ├── index.js.map
│  ├── myq-api.d.ts
│  ├── myq-api.js
│  ├── myq-api.js.map
│  ├── myq-logging.d.ts
│  ├── myq-logging.js
│  ├── myq-logging.js.map
│  ├── myq-types.d.ts
│  ├── myq-types.js
│  ├── myq-types.js.map
│  ├── settings.d.ts
│  ├── settings.js
│  └── settings.js.map
├── LICENSE.md
├── package.json
└── README.md
```

**Comment by RedondoBoony** [comment]
Hi

Thanks for your reply.
After uninstallation I had to manually delete the folder, thereafter the installation worked fine, so you can close it.

Thanks for your time, my bad.

Dominik

**Comment by vendorstring** [comment]
Hi Dominik,

could you share the fix? I have also the same connection lost problem after succesful login.

thanks

**Comment by RedondoBoony** [comment]
Hi 
Sorry I have no fix for that, I had troubles installing it, which is now working, but I also get the same Problems.
Seems like Chamberlain did change something at their end

**Comment by jarz** [comment]
@RedondoBoony since your initial issue is resolved, can you close this? Thanks.

**Comment by RedondoBoony** [comment]
Sure thanks
