### ISSUE TITLE
API Authentication Issues-myQ API Changing

### ISSUE THREAD

**Issue by benjam1nk** [hjdhjd/myq#412]
**Describe The Problem:**
During the authentication process, a failure is encountered producing a 403 Authorization Error. It is sounding like myQ has updated their “API” access once again.

**To Reproduce:**
Reproduced by utilizing any functionality of the scripts. Appears to be intermittent for the time being, with more time down than up.

**Comment by jarz** [comment]
Setting a `region` (either `east` or `west`) resolved this for the Homebridge plug-in users yesterday.

That said, today it appears to be working again (for me) without a region value.

**Comment by hjdhjd** [comment]
Not a bug…not an API change…nothing to see here…just cloud infrastructure hiccuping. Cheers. 😄
