### ISSUE TITLE
API 403 from data centers

### ISSUE THREAD

**Issue by LawJolla** [hjdhjd/myq#414]
**Describe The Problem:**

Thank you for your time and effort with this library.  To add some more color to the other 403 issues...

await account.refreshDevices() gives the following error when run from a data center.

"myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device."

I know there have been a few issues opened about a 403 and the API changing. I get the above error when run from AWS West 1 and Digital Ocean SFO. There's no error when run locally.

**To Reproduce:**

From a data center... 

    const account = new myQApi(email, password)
    await account.refreshDevices()

**Logs:**

```
2023-09-14T12:04:12.191-07:00 | myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
-- | --

```

**Screenshots:**

Not applicable

**Comment by jarz** [comment]
I think this has been covered in one of the other issues. I’m not surprised that the endpoints block calls originating from known data centers. Considering the threat model for their API, it’s a smart move. It’s only really annoying users with VPNs originating out of those data centers. 

All that said… is there a particular ask out of this issue?

**Comment by LawJolla** [comment]
@jarz agreed, I don't blame them. But I've been using the MyQ API from AWS for years without issue.  Seems odd that this issue surfaces with the other 403s.  

I use it so employees and shippers can open my business's gate at work... it's been a huge help over the years, thank you!

My ask would be to surface the fetch agent so I can proxy the request.

**Comment by danteoh** [comment]
@LawJolla I just tried deploying my lambda to us-west-2 and am getting that error.
