### ISSUE TITLE
Getting error with this package

### ISSUE THREAD

**Issue by seekex21** [hjdhjd/myq#416]
**Describe The Problem:**
I am getting error with this package 

**To Reproduce:**
`import  {myQApi} from "@hjdhjd/myq"`
`const myQ = await new myQApi('demo@mail.com','@123@')`

**Logs:**
require() of ES Module D:\Office_Client_Projects\gate_automation\node_modules\@hjdhjd\myq\dist\index.js from D:\Office_Client_Projects\gate_automation\app\Controllers\Http\HomeController.ts not supported.
Instead change the require of index.js in D:\Office_Client_Projects\gate_automation\app\Controllers\Http\HomeController.ts to a dynamic import() which is available in all CommonJS modules.

```
Show the myQ API logs here.
 "code": "ERR_REQUIRE_ESM",
```

**Screenshots:**
![image](https://github.com/hjdhjd/myq/assets/100364198/63323aa7-3d48-4886-97f9-1f46445032e6)

**Comment by jarz** [comment]
This isn’t an issue with the library, `ERR_REQUIRE_ESM` is thrown by Node.js.

There are _lots_ of search results for handling that error, here’s [one](https://stackoverflow.com/a/71805136).
