### ISSUE TITLE
Login broken with recent MyQ API updates

### ISSUE THREAD

**Issue by drysart** [hjdhjd/myq#418]
**Describe The Problem:**
Yesterday, an update was pushed out to the MyQ API that changed the behavior of the OAuth login flow slightly in a way that broke HomeAssistant's MyQ integration; and upon investigation it was determined that this implementation is impacted as well.

Logins will fail on the final /connect/token endpoint with a 401 error without a change.

For a list of the changes necessary to fix the breakage, see here: https://github.com/home-assistant/core/issues/101763#issuecomment-1758656496

**To Reproduce:**
Try to log in.

**Logs:**
If the issue isn't fixed, you'll see errors like these from this library:

```
myQ API: Invalid myQ credentials given: Check your username and password. If they are correct, the myQ API may be experiencing temporary issues. Retrying the API call.
myQ API: Switching to myQ cloud region: east.
myQ API: Invalid myQ credentials given: Check your username and password. If they are correct, the myQ API may be experiencing temporary issues. Retrying the API call.
myQ API: Switching to myQ cloud region: west.
myQ API: Invalid myQ credentials given: Check your username and password. If they are correct, the myQ API may be experiencing temporary issues. Retrying the API call.
myQ API: Switching to myQ cloud region: auto.
myQ API error: Invalid myQ credentials given: Check your username and password. If they are correct, the myQ API may be experiencing temporary issues.
```

As mentioned above, the underlying cause is a 401 from the /connect/token endpoint at the end of the OAuth login flow.

**Screenshots:**
N/A

**Comment by hjdhjd** [comment]
Thanks - I’m aware, as mentioned in another issue that was raised. We’ll wait and see and adapt, as needed. I think there’s simply not enough data yet to make a firm call on this one, given this issue has barely been an issue for a scant 24 hours so far, and for some, but not all cohorts of users. I’m not ready to make proclamations about the issue just yet - it’s simply too soon. The OAuth parameter adjustments seem innocuous enough and glad they work. We’ll see with a little time. Appreciate you raising it, and as always we’ll find a way to keep the lights on as needed. Stay tuned…
