### ISSUE TITLE
Expoential Retry Backoff Timer

### ISSUE THREAD

**Issue by spidercensus** [hjdhjd/myq#421]
**Is your feature request related to a problem? Please describe:**
I'm sure you're aware of the many people encountering rate-limiting while using this myQ library.  In [one of these issues,](https://github.com/hjdhjd/homebridge-myq/issues/1134) I suggested adding an exponential back-off timer in order to slow down clients, because there is currently no back-off timer *at all* in this libray.

**Describe the solution you'd like:**
The retry Promise will implement a sleep timer that [exponentially increases](https://en.wikipedia.org/wiki/Exponential_backoff) with each retry.

**Describe alternatives you've considered:**
A static or random back-off timer would also be somewhat useful, but given that we don't really understand the timing that leads to lock-outs, exponential will solve the problem better.  

**Additional context:**
Look at all of the first dozen issues [on this page](https://github.com/hjdhjd/homebridge-myq/issues?q=is%3Aissue+is%3Aclosed+) which were summarily closed without resolution by project maintainers.

**Comment by hjdhjd** [comment]
Please review prior issues related to this. The short answer is no. You proceed from an invalid assumption, though understandable, around what the 429 means in this context. Please review the prior issues related to this.
