### ISSUE TITLE
Simple examples of usage

### ISSUE THREAD

**Issue by kevinlieb** [hjdhjd/myq#77]
**Describe The Problem:**

There are no examples of usage

**To Reproduce:**

1. Look for examples of usage
2. Look in Homebridge code, scratch head
3. ask a question here

**Logs:**

Blankness

**Screenshots:**

Nothingness...

I'd like to see a simple example of logging in, checking what devices are present, getting a single garage door instance, checking its state and toggling its state.  I am perplexed.  So far I have:

`const { myQApi } = require('@hjdhjd/myq');

var email="myemail@yahoo.com"
var password = "somepassword"

const myq = new myQApi(email, password);

async function testme() {
  if(await(myq.refreshDevices())) {
    console.log("Await returned true");
    myq.execute("GW0E00038AF8", "close"); //did not work

  }
  else {
    console.log("Await returned false");
  }
}

testme();`

How do I get a handle on the devices?

How do I make this work?

**Comment by hjdhjd** [comment]
https://github.com/hjdhjd/myq/issues/76#issuecomment-1028525316
